export const COMPANIES = [
  {
    name: 'Spotify',
    slug: 'spotify',
    url: 'https://www.lifeatspotify.com/jobs',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback. The public careers site is not on a confirmed Greenhouse/Lever/Ashby endpoint.',
  },
  {
    name: 'Strava',
    slug: 'strava',
    url: 'https://api.ashbyhq.com/posting-api/job-board/strava?includeCompensation=false',
    parserType: 'ashby',
    enabled: true,
    notes: 'Confirmed Ashby public job board API.',
  },
  {
    name: 'Google',
    slug: 'google',
    url: 'https://www.google.com/about/careers/applications/jobs/results/?location=London%2C%20UK',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback for Google careers search filtered to London.',
  },
  {
    name: 'Microsoft',
    slug: 'microsoft',
    url: 'https://jobs.careers.microsoft.com/global/en/search?q=&lc=London%2C%20United%20Kingdom',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback for Microsoft careers search filtered to London.',
  },
  {
    name: 'DICE',
    slug: 'dice',
    url: 'https://dice.fm/careers',
    parserType: 'html',
    enabled: false,
    notes: 'Disabled in v1 because this URL currently returns 404 to fetch-based checks.',
  },
  {
    name: 'Resident Advisor',
    slug: 'resident-advisor',
    url: 'https://ra.co/about/jobs',
    parserType: 'html',
    enabled: false,
    notes: 'Disabled in v1 because this page currently returns 403 to Worker fetches.',
  },
  {
    name: 'The Economist Group',
    slug: 'the-economist-group',
    url: 'https://boards-api.greenhouse.io/v1/boards/theeconomistgroup/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
  {
    name: 'Financial Times',
    slug: 'financial-times',
    url: 'https://boards-api.greenhouse.io/v1/boards/financialtimes33/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
  {
    name: 'parkrun',
    slug: 'parkrun',
    url: 'https://www.parkrun.com/about/jobs/',
    parserType: 'html',
    enabled: false,
    notes: 'Disabled in v1 because this page currently returns 403 to Worker fetches.',
  },
  {
    name: 'London Marathon Events',
    slug: 'london-marathon-events',
    url: 'https://londonmarathongr.careers.hibob.com/jobs',
    parserType: 'html',
    enabled: true,
    notes: 'HiBob careers page. No public jobs API found; HTML fallback currently only reports jobs if links are server-rendered.',
  },
  {
    name: 'Slack',
    slug: 'slack',
    url: 'https://slack.com/careers',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback. Slack roles may redirect into Salesforce careers.',
  },
  {
    name: 'Notion',
    slug: 'notion',
    url: 'https://api.ashbyhq.com/posting-api/job-board/notion?includeCompensation=false',
    parserType: 'ashby',
    enabled: true,
    notes: 'Confirmed Ashby public job board API.',
  },
  {
    name: 'Fujifilm',
    slug: 'fujifilm',
    url: 'https://www.fujifilm.com/uk/en/careers',
    parserType: 'html',
    enabled: false,
    notes: 'Disabled in v1 because this URL currently returns 404 to fetch-based checks.',
  },
  {
    name: 'Garmin',
    slug: 'garmin',
    url: 'https://careers.garmin.com/careers-home/jobs',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback.',
  },
  {
    name: 'Sony',
    slug: 'sony',
    url: 'https://www.sonyjobs.com/',
    parserType: 'html',
    enabled: false,
    notes: 'Disabled in v1 because this page currently returns 403 to Worker fetches.',
  },
  {
    name: 'Monzo',
    slug: 'monzo',
    url: 'https://boards-api.greenhouse.io/v1/boards/monzo/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
  {
    name: 'Revolut',
    slug: 'revolut',
    url: 'https://www.revolut.com/careers/',
    parserType: 'html',
    enabled: false,
    notes: 'Disabled in v1 because this page currently returns 403 to Worker fetches.',
  },
  {
    name: 'Vinted',
    slug: 'vinted',
    url: 'https://careers.vinted.com/jobs',
    parserType: 'next-greenhouse',
    enabled: true,
    notes: 'Parses Greenhouse job payload embedded in the public Next.js page data.',
  },
  {
    name: 'Skyscanner',
    slug: 'skyscanner',
    url: 'https://boards-api.greenhouse.io/v1/boards/skyscanner/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
  {
    name: 'Looker',
    slug: 'looker',
    url: 'https://www.google.com/about/careers/applications/jobs/results/?q=Looker&location=London%2C%20UK',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback through Google careers search.',
  },
  {
    name: 'Netflix',
    slug: 'netflix',
    url: 'https://jobs.netflix.com/search?q=&location=London%2C%20United%20Kingdom',
    parserType: 'html',
    enabled: false,
    notes: 'Disabled in v1 because this URL currently returns 404 to fetch-based checks.',
  },
  {
    name: 'BBC',
    slug: 'bbc',
    url: 'https://careers.bbc.co.uk/search-jobs?location=London',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback.',
  },
  {
    name: 'Ocado',
    slug: 'ocado',
    url: 'https://boards-api.greenhouse.io/v1/boards/ocadogroup/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
  {
    name: 'Nike',
    slug: 'nike',
    url: 'https://jobs.nike.com/search?l=London%2C%20England%2C%20United%20Kingdom',
    parserType: 'html',
    enabled: false,
    notes: 'Disabled in v1 because this page currently returns 403 to Worker fetches.',
  },
  {
    name: 'Adidas',
    slug: 'adidas',
    url: 'https://jobs.adidas-group.com/search/?q=&locationsearch=London',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback for Adidas jobs search filtered to London.',
  },
  {
    name: 'Decathlon',
    slug: 'decathlon',
    url: 'https://jobs.decathlon.co.uk/go/View-all-Jobs/4978001/12/?q=&sortColumn=sort_location&sortDirection=asc',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback for Decathlon UK jobs search.',
  },
  {
    name: 'Deloitte',
    slug: 'deloitte',
    url: 'https://www.deloitte.com/uk/en/careers/job-search.html?location=London',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback.',
  },
  {
    name: 'Apple',
    slug: 'apple',
    url: 'https://jobs.apple.com/en-us/search?location=london-LND',
    parserType: 'apple',
    enabled: true,
    notes: 'HTML parser for Apple London search results.',
  },
  {
    name: 'Meta',
    slug: 'meta',
    url: 'https://www.metacareers.com/jobs?offices%5B0%5D=London%2C%20UK',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback for Meta careers search filtered to London.',
  },
  {
    name: 'YouTube',
    slug: 'youtube',
    url: 'https://www.google.com/about/careers/applications/jobs/results/?q=YouTube&location=London%2C%20UK',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback through Google careers search.',
  },
  {
    name: 'Substack',
    slug: 'substack',
    url: 'https://api.ashbyhq.com/posting-api/job-board/substack?includeCompensation=false',
    parserType: 'ashby',
    enabled: true,
    notes: 'Confirmed Ashby public job board API.',
  },
  {
    name: 'Oura',
    slug: 'oura',
    url: 'https://boards-api.greenhouse.io/v1/boards/oura/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
  {
    name: 'Starling Bank',
    slug: 'starling-bank',
    url: 'https://www.starlingbank.com/careers/',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback.',
  },
  {
    name: 'OpenAI',
    slug: 'openai',
    url: 'https://api.ashbyhq.com/posting-api/job-board/OpenAI?includeCompensation=false',
    parserType: 'ashby',
    enabled: true,
    notes: 'Confirmed Ashby public job board API.',
  },
  {
    name: 'Reddit',
    slug: 'reddit',
    url: 'https://boards-api.greenhouse.io/v1/boards/reddit/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
];
