export const COMPANIES = [
  {
    name: 'Spotify',
    slug: 'spotify',
    url: 'https://api.lifeatspotify.com/wp-json/animal/v1/job/search?l=london',
    careersUrl: 'https://www.lifeatspotify.com/jobs',
    parserType: 'spotify',
    enabled: true,
    notes: 'Confirmed public Life at Spotify jobs API filtered to London.',
  },
  {
    name: 'Strava',
    slug: 'strava',
    url: 'https://api.ashbyhq.com/posting-api/job-board/strava?includeCompensation=false',
    parserType: 'ashby',
    enabled: true,
    notes: 'Confirmed Ashby public job board API.',
  },
  {
    name: 'Google',
    slug: 'google',
    url: 'https://www.google.com/about/careers/applications/jobs/results/?location=London%2C%20UK',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback for Google careers search filtered to London.',
  },
  {
    name: 'Microsoft',
    slug: 'microsoft',
    url: 'https://apply.careers.microsoft.com/api/pcsx/search',
    careersUrl: 'https://apply.careers.microsoft.com',
    parserType: 'eightfold-pcsx',
    domain: 'microsoft.com',
    locationQuery: 'London, United Kingdom',
    pageSize: 10,
    maxPages: 3,
    enabled: true,
    notes: 'Confirmed Eightfold PCSX search API filtered to London. Three pages currently include all London matches and avoid Worker subrequest overrun.',
  },
  {
    name: 'DICE',
    slug: 'dice',
    url: 'https://dice.fm/api/v2/jobs',
    careersUrl: 'https://dice.fm/jobs',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed DICE careers page loads an array-shaped Greenhouse payload from this public API.',
  },
  {
    name: 'Resident Advisor',
    slug: 'resident-advisor',
    url: 'https://ra.co/about/jobs',
    parserType: 'html',
    enabled: false,
    notes: 'Disabled in v1 because this page currently returns 403 to Worker fetches.',
  },
  {
    name: 'The Economist Group',
    slug: 'the-economist-group',
    url: 'https://boards-api.greenhouse.io/v1/boards/theeconomistgroup/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
  {
    name: 'Financial Times',
    slug: 'financial-times',
    url: 'https://boards-api.greenhouse.io/v1/boards/financialtimes33/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
  {
    name: 'parkrun',
    slug: 'parkrun',
    url: 'https://www.parkrun.com/about/jobs/',
    parserType: 'html',
    enabled: false,
    notes: 'Disabled in v1 because this page currently returns 403 to Worker fetches.',
  },
  {
    name: 'London Marathon Events',
    slug: 'london-marathon-events',
    url: 'https://londonmarathongr.careers.hibob.com/jobs',
    parserType: 'html',
    enabled: false,
    notes: 'Disabled for now: HiBob page does not expose server-rendered job links to fetch-based parsing, so it returns zero parsed jobs and consumes Worker subrequest budget.',
  },
  {
    name: 'Slack',
    slug: 'slack',
    url: 'https://slack.com/careers',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback. Slack roles may redirect into Salesforce careers.',
  },
  {
    name: 'Notion',
    slug: 'notion',
    url: 'https://api.ashbyhq.com/posting-api/job-board/notion?includeCompensation=false',
    parserType: 'ashby',
    enabled: true,
    notes: 'Confirmed Ashby public job board API.',
  },
  {
    name: 'Fujifilm',
    slug: 'fujifilm',
    url: 'https://externalhub-fujifilmeu.icims.com/jobs/search?ss=1&in_iframe=1',
    careersUrl: 'https://www.fujifilm.com/uk/en/about/career',
    parserType: 'icims',
    enabled: true,
    notes: 'Confirmed Fujifilm UK careers page links to Fujifilm Europe iCIMS portals. Current UK-specific portal has zero jobs; this wider Europe hub is parsed and London-filtered.',
  },
  {
    name: 'Garmin',
    slug: 'garmin',
    url: 'https://careers.garmin.com/api/jobs?keywords=&location=London%2C%20UK&sortBy=posted_date',
    parserType: 'jibe',
    pageSize: 10,
    maxPages: 2,
    enabled: true,
    notes: 'Confirmed Jibe careers API filtered to London. Current official facet returns zero London jobs.',
  },
  {
    name: 'Sony',
    slug: 'sony',
    url: 'https://sonyglobal.wd1.myworkdayjobs.com/wday/cxs/sonyglobal/SonyGlobalCareers/jobs',
    careersUrl: 'https://sonyglobal.wd1.myworkdayjobs.com/SonyGlobalCareers',
    parserType: 'workday',
    locationQuery: 'London',
    pageSize: 20,
    maxPages: 3,
    enabled: true,
    notes: 'Confirmed Sony jobs page embeds Sony Global Workday; Workday search is filtered to London.',
  },
  {
    name: 'Monzo',
    slug: 'monzo',
    url: 'https://boards-api.greenhouse.io/v1/boards/monzo/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
  {
    name: 'Revolut',
    slug: 'revolut',
    url: 'https://r.jina.ai/http://https://www.revolut.com/careers/',
    careersUrl: 'https://www.revolut.com',
    parserType: 'revolut-next',
    enabled: true,
    notes: 'Parses the official Revolut careers Next.js positions payload via a fetch-only reader because direct Worker fetches are Cloudflare-challenged.',
  },
  {
    name: 'Vinted',
    slug: 'vinted',
    url: 'https://careers.vinted.com/jobs',
    parserType: 'next-greenhouse',
    greenhouseDataMapKey: 'vinteden',
    enabled: true,
    notes: 'Parses English Greenhouse job payload embedded in the public Next.js page data.',
  },
  {
    name: 'Skyscanner',
    slug: 'skyscanner',
    url: 'https://boards-api.greenhouse.io/v1/boards/skyscanner/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
  {
    name: 'Looker',
    slug: 'looker',
    url: 'https://www.google.com/about/careers/applications/jobs/results/?q=Looker&location=London%2C%20UK',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback through Google careers search.',
  },
  {
    name: 'Netflix',
    slug: 'netflix',
    url: 'https://explore.jobs.netflix.net/careers?query=&location=London',
    parserType: 'eightfold-embedded',
    enabled: true,
    notes: 'Parses Eightfold smartApplyData embedded in Netflix London search HTML.',
  },
  {
    name: 'BBC',
    slug: 'bbc',
    url: 'https://careers.bbc.co.uk/services/recruiting/v1/jobs',
    careersUrl: 'https://careers.bbc.co.uk',
    parserType: 'successfactors',
    locale: 'en_GB',
    locationQuery: 'London',
    enabled: true,
    notes: 'Confirmed SAP SuccessFactors Recruiting API filtered to London.',
  },
  {
    name: 'Ocado',
    slug: 'ocado',
    url: 'https://boards-api.greenhouse.io/v1/boards/ocadogroup/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
  {
    name: 'Nike',
    slug: 'nike',
    url: 'https://nike.wd1.myworkdayjobs.com/wday/cxs/nike/nke/jobs',
    careersUrl: 'https://nike.wd1.myworkdayjobs.com/nke',
    parserType: 'workday',
    pageSize: 20,
    maxPages: 2,
    searches: [
      { searchText: 'London', maxPages: 2 },
      { searchText: 'Battersea', maxPages: 1, locationHint: 'London' },
    ],
    enabled: true,
    notes: 'Confirmed Nike Workday API. Searches London plus Battersea because Battersea roles do not include London in Workday location text.',
  },
  {
    name: 'Adidas',
    slug: 'adidas',
    url: 'https://jobs.adidas-group.com/search/?q=&locationsearch=London',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback for Adidas jobs search filtered to London.',
  },
  {
    name: 'Decathlon',
    slug: 'decathlon',
    url: 'https://jobs.decathlon.co.uk/go/View-all-Jobs/4978001/12/?q=&sortColumn=sort_location&sortDirection=asc',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback for Decathlon UK jobs search.',
  },
  {
    name: 'Deloitte',
    slug: 'deloitte',
    url: 'https://www.deloitte.com/uk/en/careers/job-search.html?location=London',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback.',
  },
  {
    name: 'Apple',
    slug: 'apple',
    url: 'https://jobs.apple.com/en-us/search?location=london-LND',
    parserType: 'apple',
    enabled: true,
    notes: 'Parses paginated Apple search hydration data for the London location filter.',
  },
  {
    name: 'Meta',
    slug: 'meta',
    url: 'https://www.metacareers.com/jobs?offices%5B0%5D=London%2C%20UK',
    parserType: 'meta-graphql',
    offices: ['London, UK'],
    graphqlDocId: '29615178951461218',
    enabled: true,
    notes: 'Confirmed Meta careers Relay GraphQL search filtered to London.',
  },
  {
    name: 'YouTube',
    slug: 'youtube',
    url: 'https://www.google.com/about/careers/applications/jobs/results/?q=YouTube&location=London%2C%20UK',
    parserType: 'html',
    enabled: true,
    notes: 'HTML fallback through Google careers search.',
  },
  {
    name: 'Substack',
    slug: 'substack',
    url: 'https://api.ashbyhq.com/posting-api/job-board/substack?includeCompensation=false',
    parserType: 'ashby',
    enabled: true,
    notes: 'Confirmed Ashby public job board API.',
  },
  {
    name: 'Oura',
    slug: 'oura',
    url: 'https://boards-api.greenhouse.io/v1/boards/oura/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
  {
    name: 'Starling Bank',
    slug: 'starling-bank',
    url: 'https://www.starlingbank.com/api/job-listings',
    parserType: 'workable',
    enabled: true,
    notes: 'Confirmed Starling API exposing Workable-backed job listings.',
  },
  {
    name: 'OpenAI',
    slug: 'openai',
    url: 'https://api.ashbyhq.com/posting-api/job-board/OpenAI?includeCompensation=false',
    parserType: 'ashby',
    enabled: true,
    notes: 'Confirmed Ashby public job board API.',
  },
  {
    name: 'Reddit',
    slug: 'reddit',
    url: 'https://boards-api.greenhouse.io/v1/boards/reddit/jobs?content=true',
    parserType: 'greenhouse',
    enabled: true,
    notes: 'Confirmed Greenhouse public job board API.',
  },
];
